name: "GreetContributor"
on:
  issues:
    
jobs:
  GreetCommitter: 
    runs-on: ubuntu-latest
    steps:
    - name: "Greet contributor"
      uses: ibakshay/greet-contributors-action@696c3f84707d0a6a5ea30141c3643041dfd7b749
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
