name: "GreetContributor"
on:
  pull_request:
    types: [opened,synchronize]
    
jobs:
  GreetCommitter: 
    runs-on: ubuntu-latest
    steps:
    - name: "Greet contributor"
      uses: ibakshay/greet-contributors-action@7e36903e37bafb39146576eafb8b909afe32f9f2
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
